In [ ]:
import numpy as np
import torch
from smplpytorch.pytorch.smpl_layer import SMPL_Layer
from display_utils import display_model

cuda = False
batch_size = 1
smpl_layer = SMPL_Layer(center_idx=0, gender='neutral', model_root='smplpytorch/native/models')
file = np.load("C:/Users/lalas/Downloads/file.npz")

for frame_index in range(file['global_orient'].shape[0]-1):
    global_orient = file['global_orient'][frame_index]
    global_orient[0] = 0
    global_orient[1] = 0
    global_orient[2] = 0
    body_shape = file['betas'][frame_index]
    body_pose = file['body_pose'][frame_index]
    print(global_orient)
    #print("Frame Index:", frame_index)
    #print("Shapes:", global_orient.shape, body_shape.shape, body_pose.shape)

    pose_params = torch.cat([torch.tensor(global_orient).view(1, -1), torch.tensor(body_pose).view(1, -1)], dim=1)
    shape_params = torch.tensor(body_shape.reshape(batch_size, -1), dtype=torch.float32)
    #print("Tensor Shapes:", pose_params.shape, shape_params.shape)
    verts, Jtr = smpl_layer(pose_params, th_betas=shape_params)
    #print(Jtr.shape)
    torch.save(Jtr, f'joint/joint_{frame_index}.pt')
    display_model({'verts': verts.cpu().detach(), 'joints': Jtr.cpu().detach()}, model_faces=smpl_layer.th_faces,with_joints=True, kintree_table=smpl_layer.kintree_table, savepath=f'pic/image_{frame_index}.png', show=False)

print("Processing complete.")

C:\Users\lalas\smplpytorch\smplpytorch\pytorch\smpl_layer.py:41: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  C:\b\abs_bao0hdcrdh\croot\pytorch_1675190257512\work\torch\csrc\utils\tensor_numpy.cpp:178.)
  torch.Tensor(smpl_data['betas'].r).unsqueeze(0))


[0. 0. 0.]
Saving figure at pic/image_0.png.
[0. 0. 0.]
Saving figure at pic/image_1.png.
[0. 0. 0.]
Saving figure at pic/image_2.png.
[0. 0. 0.]
Saving figure at pic/image_3.png.
[0. 0. 0.]
Saving figure at pic/image_4.png.
[0. 0. 0.]
Saving figure at pic/image_5.png.
[0. 0. 0.]
Saving figure at pic/image_6.png.
[0. 0. 0.]
Saving figure at pic/image_7.png.
[0. 0. 0.]
Saving figure at pic/image_8.png.
[0. 0. 0.]
Saving figure at pic/image_9.png.
[0. 0. 0.]
Saving figure at pic/image_10.png.
[0. 0. 0.]
Saving figure at pic/image_11.png.
[0. 0. 0.]
Saving figure at pic/image_12.png.
[0. 0. 0.]
Saving figure at pic/image_13.png.
[0. 0. 0.]
Saving figure at pic/image_14.png.
[0. 0. 0.]
Saving figure at pic/image_15.png.
[0. 0. 0.]
Saving figure at pic/image_16.png.
[0. 0. 0.]
Saving figure at pic/image_17.png.
[0. 0. 0.]
Saving figure at pic/image_18.png.
[0. 0. 0.]
Saving figure at pic/image_19.png.
[0. 0. 0.]
Saving figure at pic/image_20.png.


C:\Users\lalas\smplpytorch\display_utils.py:21: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig = plt.figure()


[0. 0. 0.]
Saving figure at pic/image_21.png.
[0. 0. 0.]
Saving figure at pic/image_22.png.
[0. 0. 0.]
Saving figure at pic/image_23.png.
[0. 0. 0.]
Saving figure at pic/image_24.png.
[0. 0. 0.]
Saving figure at pic/image_25.png.
[0. 0. 0.]
Saving figure at pic/image_26.png.
[0. 0. 0.]
Saving figure at pic/image_27.png.
[0. 0. 0.]
Saving figure at pic/image_28.png.
[0. 0. 0.]
Saving figure at pic/image_29.png.
[0. 0. 0.]
Saving figure at pic/image_30.png.
[0. 0. 0.]
Saving figure at pic/image_31.png.
[0. 0. 0.]
Saving figure at pic/image_32.png.
[0. 0. 0.]
Saving figure at pic/image_33.png.
[0. 0. 0.]
Saving figure at pic/image_34.png.
[0. 0. 0.]
Saving figure at pic/image_35.png.
[0. 0. 0.]
Saving figure at pic/image_36.png.
[0. 0. 0.]
Saving figure at pic/image_37.png.
[0. 0. 0.]
Saving figure at pic/image_38.png.
[0. 0. 0.]
Saving figure at pic/image_39.png.
[0. 0. 0.]
Saving figure at pic/image_40.png.
[0. 0. 0.]
Saving figure at pic/image_41.png.
[0. 0. 0.]
Saving figure at pic/im

[0. 0. 0.]
Saving figure at pic/image_197.png.
[0. 0. 0.]
Saving figure at pic/image_198.png.
[0. 0. 0.]
Saving figure at pic/image_199.png.
[0. 0. 0.]
Saving figure at pic/image_200.png.
[0. 0. 0.]
Saving figure at pic/image_201.png.
[0. 0. 0.]
Saving figure at pic/image_202.png.
[0. 0. 0.]
Saving figure at pic/image_203.png.
[0. 0. 0.]
Saving figure at pic/image_204.png.
[0. 0. 0.]
Saving figure at pic/image_205.png.
[0. 0. 0.]
Saving figure at pic/image_206.png.
[0. 0. 0.]
Saving figure at pic/image_207.png.
[0. 0. 0.]
Saving figure at pic/image_208.png.
[0. 0. 0.]
Saving figure at pic/image_209.png.
[0. 0. 0.]
Saving figure at pic/image_210.png.
[0. 0. 0.]
Saving figure at pic/image_211.png.
[0. 0. 0.]
Saving figure at pic/image_212.png.
[0. 0. 0.]
Saving figure at pic/image_213.png.
[0. 0. 0.]
Saving figure at pic/image_214.png.
[0. 0. 0.]
Saving figure at pic/image_215.png.
[0. 0. 0.]
Saving figure at pic/image_216.png.
[0. 0. 0.]
Saving figure at pic/image_217.png.
[0. 0. 0.]
Sa

[0. 0. 0.]
Saving figure at pic/image_372.png.
[0. 0. 0.]
Saving figure at pic/image_373.png.
[0. 0. 0.]
Saving figure at pic/image_374.png.
[0. 0. 0.]
Saving figure at pic/image_375.png.
[0. 0. 0.]
Saving figure at pic/image_376.png.
[0. 0. 0.]
Saving figure at pic/image_377.png.
[0. 0. 0.]
Saving figure at pic/image_378.png.
[0. 0. 0.]
Saving figure at pic/image_379.png.
[0. 0. 0.]
Saving figure at pic/image_380.png.
[0. 0. 0.]
Saving figure at pic/image_381.png.
[0. 0. 0.]
Saving figure at pic/image_382.png.
[0. 0. 0.]
Saving figure at pic/image_383.png.
[0. 0. 0.]
Saving figure at pic/image_384.png.
[0. 0. 0.]
Saving figure at pic/image_385.png.
[0. 0. 0.]
Saving figure at pic/image_386.png.
[0. 0. 0.]
Saving figure at pic/image_387.png.
[0. 0. 0.]
Saving figure at pic/image_388.png.
[0. 0. 0.]
Saving figure at pic/image_389.png.
[0. 0. 0.]
Saving figure at pic/image_390.png.
[0. 0. 0.]
Saving figure at pic/image_391.png.
[0. 0. 0.]
Saving figure at pic/image_392.png.
[0. 0. 0.]
Sa

[0. 0. 0.]
Saving figure at pic/image_547.png.
[0. 0. 0.]
Saving figure at pic/image_548.png.
[0. 0. 0.]
Saving figure at pic/image_549.png.
[0. 0. 0.]
Saving figure at pic/image_550.png.
[0. 0. 0.]
Saving figure at pic/image_551.png.
[0. 0. 0.]
Saving figure at pic/image_552.png.
[0. 0. 0.]
Saving figure at pic/image_553.png.
[0. 0. 0.]
Saving figure at pic/image_554.png.
[0. 0. 0.]
Saving figure at pic/image_555.png.
[0. 0. 0.]
Saving figure at pic/image_556.png.
[0. 0. 0.]
Saving figure at pic/image_557.png.
[0. 0. 0.]
Saving figure at pic/image_558.png.
[0. 0. 0.]
Saving figure at pic/image_559.png.
[0. 0. 0.]
Saving figure at pic/image_560.png.
[0. 0. 0.]
Saving figure at pic/image_561.png.
[0. 0. 0.]
Saving figure at pic/image_562.png.
[0. 0. 0.]
Saving figure at pic/image_563.png.
[0. 0. 0.]
Saving figure at pic/image_564.png.
[0. 0. 0.]
Saving figure at pic/image_565.png.
[0. 0. 0.]
Saving figure at pic/image_566.png.
[0. 0. 0.]
Saving figure at pic/image_567.png.
[0. 0. 0.]
Sa

[0. 0. 0.]
Saving figure at pic/image_722.png.
[0. 0. 0.]
Saving figure at pic/image_723.png.
[0. 0. 0.]
Saving figure at pic/image_724.png.
[0. 0. 0.]
Saving figure at pic/image_725.png.
[0. 0. 0.]
Saving figure at pic/image_726.png.
[0. 0. 0.]
Saving figure at pic/image_727.png.
[0. 0. 0.]
Saving figure at pic/image_728.png.
[0. 0. 0.]
Saving figure at pic/image_729.png.
[0. 0. 0.]
Saving figure at pic/image_730.png.
[0. 0. 0.]
Saving figure at pic/image_731.png.
[0. 0. 0.]
Saving figure at pic/image_732.png.
[0. 0. 0.]
Saving figure at pic/image_733.png.
[0. 0. 0.]
Saving figure at pic/image_734.png.
[0. 0. 0.]
Saving figure at pic/image_735.png.
[0. 0. 0.]
Saving figure at pic/image_736.png.
[0. 0. 0.]
Saving figure at pic/image_737.png.
[0. 0. 0.]
Saving figure at pic/image_738.png.
[0. 0. 0.]
Saving figure at pic/image_739.png.
[0. 0. 0.]
Saving figure at pic/image_740.png.
[0. 0. 0.]
Saving figure at pic/image_741.png.
[0. 0. 0.]
Saving figure at pic/image_742.png.
[0. 0. 0.]
Sa

[0. 0. 0.]
Saving figure at pic/image_897.png.
[0. 0. 0.]
Saving figure at pic/image_898.png.
[0. 0. 0.]
Saving figure at pic/image_899.png.
[0. 0. 0.]
Saving figure at pic/image_900.png.
[0. 0. 0.]
Saving figure at pic/image_901.png.
[0. 0. 0.]
Saving figure at pic/image_902.png.
[0. 0. 0.]
Saving figure at pic/image_903.png.
[0. 0. 0.]
Saving figure at pic/image_904.png.
[0. 0. 0.]
Saving figure at pic/image_905.png.
[0. 0. 0.]
Saving figure at pic/image_906.png.
[0. 0. 0.]
Saving figure at pic/image_907.png.
[0. 0. 0.]
Saving figure at pic/image_908.png.
[0. 0. 0.]
Saving figure at pic/image_909.png.
[0. 0. 0.]
Saving figure at pic/image_910.png.
[0. 0. 0.]
Saving figure at pic/image_911.png.
[0. 0. 0.]
Saving figure at pic/image_912.png.
[0. 0. 0.]
Saving figure at pic/image_913.png.
[0. 0. 0.]
Saving figure at pic/image_914.png.
[0. 0. 0.]
Saving figure at pic/image_915.png.
[0. 0. 0.]
Saving figure at pic/image_916.png.
[0. 0. 0.]
Saving figure at pic/image_917.png.
[0. 0. 0.]
Sa

[0. 0. 0.]
Saving figure at pic/image_1070.png.
[0. 0. 0.]
Saving figure at pic/image_1071.png.
[0. 0. 0.]
Saving figure at pic/image_1072.png.
[0. 0. 0.]
Saving figure at pic/image_1073.png.
[0. 0. 0.]
Saving figure at pic/image_1074.png.
[0. 0. 0.]
Saving figure at pic/image_1075.png.
[0. 0. 0.]
Saving figure at pic/image_1076.png.
[0. 0. 0.]
Saving figure at pic/image_1077.png.
[0. 0. 0.]
Saving figure at pic/image_1078.png.
[0. 0. 0.]
Saving figure at pic/image_1079.png.
[0. 0. 0.]
Saving figure at pic/image_1080.png.
[0. 0. 0.]
Saving figure at pic/image_1081.png.
[0. 0. 0.]
Saving figure at pic/image_1082.png.
[0. 0. 0.]
Saving figure at pic/image_1083.png.
[0. 0. 0.]
Saving figure at pic/image_1084.png.
[0. 0. 0.]
Saving figure at pic/image_1085.png.
[0. 0. 0.]
Saving figure at pic/image_1086.png.
[0. 0. 0.]
Saving figure at pic/image_1087.png.
[0. 0. 0.]
Saving figure at pic/image_1088.png.
[0. 0. 0.]
Saving figure at pic/image_1089.png.
[0. 0. 0.]
Saving figure at pic/image_10

In [ ]:
file = np.load("C:/Users/lalas/Downloads/file.npz")
